/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Retorna status da API.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Retorna apenas vagas com status 'open'.
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Cria uma nova vaga com suas questões associadas.
         */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Retorna detalhes de uma vaga específica.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Job
         * @description Atualiza dados básicos da vaga.
         */
        patch: operations["update_job_api_v1_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Job Questions
         * @description Atualiza as questões da vaga (bloqueado se houver candidatos).
         */
        patch: operations["update_job_questions_api_v1_jobs__job_id__questions_patch"];
        trace?: never;
    };
    "/api/v1/recruiter/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recruiter Stats
         * @description Retorna estatísticas consolidadas para o dashboard do recrutador.
         */
        get: operations["get_recruiter_stats_api_v1_recruiter_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiter/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recruiter Jobs
         * @description Retorna todas as vagas com contagem de candidatos para o painel de recrutador.
         */
        get: operations["list_recruiter_jobs_api_v1_recruiter_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiter/jobs/{job_id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Applications
         * @description Lista todos os candidatos que se aplicaram a uma vaga específica.
         */
        get: operations["list_job_applications_api_v1_recruiter_jobs__job_id__applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Application
         * @description Submete uma candidatura completa: dados do perfil, resultado do teste e currículo (PDF).
         *     Garante que não haja duplicidade de candidatura para a mesma vaga.
         */
        post: operations["submit_application_api_v1_applications_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Cria um novo usuário com senha hashed, validação de CPF e idade.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Valida credenciais e retorna dados do usuário com token JWT.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationRead
         * @description Esquema para leitura (saída da API).
         */
        ApplicationRead: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Candidate Email
             * Format: email
             */
            candidate_email: string;
            /** Profile Data */
            profile_data: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
            /** Message */
            message?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Resume Url */
            resume_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_submit_application_api_v1_applications_submit_post */
        Body_submit_application_api_v1_applications_submit_post: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Candidate Email
             * Format: email
             */
            candidate_email: string;
            /** Profile Data */
            profile_data: string;
            /** Score */
            score: number;
            /** File */
            file: string;
            /** Message */
            message?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Title */
            title: string;
            /** Area */
            area: string;
            /** Description */
            description?: string | null;
            /** Contract Type */
            contract_type?: string | null;
            /** Schedule */
            schedule?: string | null;
            /** Workplace */
            workplace?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Assignments */
            assignments?: string | null;
            /** Questions */
            questions: components["schemas"]["QuestionCreate"][];
        };
        /** JobQuestionsUpdate */
        JobQuestionsUpdate: {
            /** Questions */
            questions: components["schemas"]["QuestionCreate"][];
        };
        /** JobRead */
        JobRead: {
            /** Title */
            title: string;
            /** Area */
            area: string;
            /** Description */
            description?: string | null;
            /** Contract Type */
            contract_type?: string | null;
            /** Schedule */
            schedule?: string | null;
            /** Workplace */
            workplace?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Assignments */
            assignments?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Questions */
            questions: components["schemas"]["QuestionRead"][];
        };
        /**
         * JobRecruiter
         * @description Versão para o painel do recrutador, inclui contador de candidatos.
         */
        JobRecruiter: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Area */
            area: string;
            /** Workplace */
            workplace?: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Applicant Count
             * @default 0
             */
            applicant_count: number;
        };
        /**
         * JobSimple
         * @description Versão simplificada para listagem pública.
         */
        JobSimple: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Area */
            area: string;
            /** Workplace */
            workplace?: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "open" | "closed";
        /** JobUpdate */
        JobUpdate: {
            /** Title */
            title?: string | null;
            /** Area */
            area?: string | null;
            /** Description */
            description?: string | null;
            /** Contract Type */
            contract_type?: string | null;
            /** Schedule */
            schedule?: string | null;
            /** Workplace */
            workplace?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Assignments */
            assignments?: string | null;
            status?: components["schemas"]["JobStatus"] | null;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /**
             * Text
             * @description O enunciado da questão
             */
            text: string;
            /**
             * Options
             * @description Lista de opções de resposta
             */
            options: string[];
            /**
             * Correct Index
             * @description Índice da opção correta
             */
            correct_index: number;
        };
        /** QuestionRead */
        QuestionRead: {
            /**
             * Text
             * @description O enunciado da questão
             */
            text: string;
            /**
             * Options
             * @description Lista de opções de resposta
             */
            options: string[];
            /**
             * Correct Index
             * @description Índice da opção correta
             */
            correct_index: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** RecruiterStats */
        RecruiterStats: {
            /** Total Jobs */
            total_jobs: number;
            /** Active Jobs */
            active_jobs: number;
            /** Total Applications */
            total_applications: number;
            /** New Applications Today */
            new_applications_today: number;
        };
        /**
         * Token
         * @description Schema para retorno de token de acesso.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /** Picture */
            picture?: string | null;
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Cpf */
            cpf: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** @default candidate */
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "candidate" | "recruiter";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSimple"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_v1_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_questions_api_v1_jobs__job_id__questions_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-simulate-has-applicants"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobQuestionsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recruiter_stats_api_v1_recruiter_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecruiterStats"];
                };
            };
        };
    };
    list_recruiter_jobs_api_v1_recruiter_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecruiter"][];
                };
            };
        };
    };
    list_job_applications_api_v1_recruiter_jobs__job_id__applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_v1_applications_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_application_api_v1_applications_submit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
