"""Add cpf and birth_date to users

Revision ID: 1f420fdbbf49
Revises: 0109a6f8a089
Create Date: 2026-04-07 20:28:37.968527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f420fdbbf49'
down_revision: Union[str, None] = '0109a6f8a089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
