"""add_deleted_at_to_jobs

Revision ID: e523e7b35a5b
Revises: a9b2c3d4e5f6
Create Date: 2026-06-02 17:43:48.964461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e523e7b35a5b'
down_revision: Union[str, None] = 'a9b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'deleted_at')
    # ### end Alembic commands ###
